spring.application.name=API-GATEWAY

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.mvc.discovery.locator.enabled=true
spring.cloud.gateway.mvc.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.mvc.routes[1].id=user-service
spring.cloud.gateway.mvc.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/users/**

spring.cloud.gateway.mvc.routes[2].id=vendor-service
spring.cloud.gateway.mvc.routes[2].uri=lb://USER-SERVICE
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/vendors/**

spring.cloud.gateway.mvc.routes[3].id=menu-service
spring.cloud.gateway.mvc.routes[3].uri=lb://MENU-SERVICE
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/menus/**

spring.cloud.gateway.mvc.routes[4].id=cart-service
spring.cloud.gateway.mvc.routes[4].uri=lb://CART-SERVICE
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/cart/**

spring.cloud.gateway.mvc.routes[5].id=order-service
spring.cloud.gateway.mvc.routes[5].uri=lb://ORDER-SERVICE
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/orders/**

spring.cloud.gateway.mvc.routes[6].id=feedback-service
spring.cloud.gateway.mvc.routes[6].uri=lb://FEEDBACK-SERVICE
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/feedback/**
